apiVersion: apiextensions.crossplane.io/v2
kind: CompositeResourceDefinition
metadata:
  name: arbitraryuids.example.crossplane.io
spec:
  group: example.crossplane.io
  names:
    kind: ArbitraryUID
    plural: arbitraryuids
  scope: Cluster
  versions:
    - name: v1
      served: true
      referenceable: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties: {}
            status:
              type: object
              properties:
                atFunction:
                  type: object
                  x-kubernetes-preserve-unknown-fields: true
