apiVersion: aws.upbound.io/v1beta1
kind: ProviderConfig
metadata:
  labels:
    account: demo
  name: demo
spec:
  assumeRoleChain:
    - roleARN: arn:aws:iam::000000000001:role/eks-test-assume-role
  credentials:
    source: IRSA
