apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: shell-example
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: shell
      functionRef:
        name: function-shell
      input:
        apiVersion: shell.fn.crossplane.io/v1alpha1
        kind: Parameters
        shellEnvVars:
          - key: ECHO
            fieldRef:
              path: spec.field
            type: FieldRef
          - key: OPTIONAL
            type: FieldRef
            fieldRef:
              path: spec.optional
              policy: Optional
              defaultValue: "defaultValue from Composition"
          - key: FN_STDOUT
            type: FieldRef
            fieldRef:
              path: status.atFunction.shell.stdout
              policy: Optional
              defaultValue: ""
        shellCommand: |
           echo "echo: ${ECHO} optional: ${OPTIONAL}" &&
           if [ "$FN_STDOUT" != "" ]; then
             echo "status.atFunction.shell.stdout" is populated
           fi
        stdoutField: status.atFunction.shell.stdout
        stderrField: status.atFunction.shell.stderr
