//go:build !ignore_autogenerated

// Code generated by controller-gen. DO NOT EDIT.

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *Parameters) DeepCopyInto(out *Parameters) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.ShellEnvVarsSecretRef = in.ShellEnvVarsSecretRef
	if in.ShellEnvVars != nil {
		in, out := &in.ShellEnvVars, &out.ShellEnvVars
		*out = make([]ShellEnvVar, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new Parameters.
func (in *Parameters) DeepCopy() *Parameters {
	if in == nil {
		return nil
	}
	out := new(Parameters)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *Parameters) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShellEnvVar) DeepCopyInto(out *ShellEnvVar) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShellEnvVar.
func (in *ShellEnvVar) DeepCopy() *ShellEnvVar {
	if in == nil {
		return nil
	}
	out := new(ShellEnvVar)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ShellEnvVarsSecretRef) DeepCopyInto(out *ShellEnvVarsSecretRef) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ShellEnvVarsSecretRef.
func (in *ShellEnvVarsSecretRef) DeepCopy() *ShellEnvVarsSecretRef {
	if in == nil {
		return nil
	}
	out := new(ShellEnvVarsSecretRef)
	in.DeepCopyInto(out)
	return out
}
