apiVersion: apiextensions.crossplane.io/v1
kind: Composition
metadata:
  name: shell-example
spec:
  compositeTypeRef:
    apiVersion: example.crossplane.io/v1
    kind: XR
  mode: Pipeline
  pipeline:
    - step: shell
      functionRef:
        name: function-shell
      input:
        apiVersion: shell.fn.crossplane.io/v1alpha1
        kind: Parameters
        cacheTTL: 5m
        shellEnvVars:
          - key: ECHO
            value: "SGVsbG8gZnJvbSBzaGVsbAo="
        shellCommand: |
           echo ${ECHO}|base64 -d|sed s/^h/H/
        stdoutField: status.atFunction.shell.stdout
        stderrField: status.atFunction.shell.stderr
