---
apiVersion: pkg.crossplane.io/v1
kind: Function
metadata:
  name: function-shell
  annotations:
    # This tells crossplane beta render to connect to the function locally.
    render.crossplane.io/runtime: Development
spec:
  # This is ignored when using the Development runtime.
  package: xpkg.upbound.io/crossplane-contrib/function-shell:v0.5.0
